const ACTIONS = {
  JOIN_SERVER: 'JOIN_SERVER',
  SET_WINNER: 'SET_WINNER',
  SET_GAME_DATA: 'SET_GAME_DATA',
  SET_PLAYER_NUMBER: 'SET_PLAYER_NUMBER',
  SET_ROOM: 'SET_ROOM',
  SET_TURN: 'SET_TURN',
  SET_ERRORS: 'SET_ERRORS',
  SET_ERROR_EXIST: 'SET_ERROR_EXIST',
};

export default ACTIONS;
